"""add_products_suppliers_customers_sales_payments

Revision ID: 97914c9f4370
Revises: 79b2ab93ebd5
Create Date: 2026-08-25 19:01:48.643467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97914c9f4370'
down_revision: Union[str, None] = '79b2ab93ebd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('type_client', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('conditions_paiement_jours', sa.Integer(), nullable=False),
    sa.Column('encours_actuel', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_nom'), 'customers', ['nom'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('prix_achat_ref', sa.Float(), nullable=True),
    sa.Column('stock_kg', sa.Float(), nullable=False),
    sa.Column('seuil_alerte_kg', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_nom'), 'products', ['nom'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_nom'), 'suppliers', ['nom'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_vente', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('montant_total_ttc', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('montant_restant_du', sa.Float(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_date_vente'), 'sales', ['date_vente'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('type_tiers', sa.String(length=20), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('mode_paiement', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['depences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_date_paiement'), 'payments', ['date_paiement'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_purchase_id'), 'payments', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_payments_sale_id'), 'payments', ['sale_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('nom_produit_texte', sa.String(length=150), nullable=True),
    sa.Column('kilo_vendu', sa.Float(), nullable=False),
    sa.Column('prix_unitaire_kg', sa.Float(), nullable=False),
    sa.Column('sous_total_ligne', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_id'), 'sale_items', ['id'], unique=False)
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    # Colonnes ajoutées en 2 temps (nullable=True puis backfill puis NOT NULL
    op.add_column('depences', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('depences', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('depences', sa.Column('montant_restant_du', sa.Float(), nullable=True))
    op.add_column('depences', sa.Column('date_echeance', sa.Date(), nullable=True))
    op.add_column('depences', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # Backfill montant_restant_du (mettre prix si existant sinon 0)
    op.execute(
        "UPDATE depences SET montant_restant_du = COALESCE(prix, 0.0) "
        "WHERE montant_restant_du IS NULL"
    )
    op.execute("UPDATE depences SET created_at = NOW() WHERE created_at IS NULL")
    # Repasser NOT NULL
    op.alter_column('depences', 'montant_restant_du', nullable=False, existing_type=sa.Float())
    op.alter_column('depences', 'created_at', nullable=False,
                    existing_type=sa.DateTime(timezone=True),
                    existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_depences_product_id'), 'depences', ['product_id'], unique=False)
    op.create_index(op.f('ix_depences_supplier_id'), 'depences', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'depences', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'depences', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # users.created_at (même logique)
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('users', 'created_at', nullable=False,
                    existing_type=sa.DateTime(timezone=True),
                    existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'depences', type_='foreignkey')
    op.drop_constraint(None, 'depences', type_='foreignkey')
    op.drop_index(op.f('ix_depences_supplier_id'), table_name='depences')
    op.drop_index(op.f('ix_depences_product_id'), table_name='depences')
    op.drop_column('depences', 'created_at')
    op.drop_column('depences', 'date_echeance')
    op.drop_column('depences', 'montant_restant_du')
    op.drop_column('depences', 'product_id')
    op.drop_column('depences', 'supplier_id')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_payments_sale_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_purchase_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_date_paiement'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_date_vente'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_suppliers_nom'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_products_nom'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_nom'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
