"""remove_unique_constraints_depences

Revision ID: aaaa6a45d4e0
Revises: 
Create Date: 2026-08-25 13:50:22.339937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaaa6a45d4e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('depences', 'joudate',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint('depences_kilo_key', 'depences', type_='unique')
    op.drop_constraint('depences_nonpaye_key', 'depences', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('depences_nonpaye_key', 'depences', ['nomproduit'])
    op.create_unique_constraint('depences_kilo_key', 'depences', ['kilo'])
    op.alter_column('depences', 'joudate',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
