"""add fournitures, ventes, commandes_retour tables

Revision ID: b1c2d3e4f5a6
Revises: 491f357c0d69
Create Date: 2026-09-01 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5a6'
down_revision: Union[str, None] = '491f357c0d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fournitures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('nom_produit_texte', sa.String(length=150), nullable=False),
    sa.Column('date_obtenu', sa.Date(), nullable=False),
    sa.Column('origine', sa.String(length=200), nullable=False),
    sa.Column('nom_fournisseur', sa.String(length=200), nullable=False),
    sa.Column('kilo_produit', sa.Float(), nullable=False),
    sa.Column('prix_par_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fournitures_date_obtenu'), 'fournitures', ['date_obtenu'], unique=False)
    op.create_index(op.f('ix_fournitures_id'), 'fournitures', ['id'], unique=False)
    op.create_index(op.f('ix_fournitures_nom_fournisseur'), 'fournitures', ['nom_fournisseur'], unique=False)
    op.create_index(op.f('ix_fournitures_product_id'), 'fournitures', ['product_id'], unique=False)

    op.create_table('ventes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('nom_produit_texte', sa.String(length=150), nullable=False),
    sa.Column('fourniture_id', sa.Integer(), nullable=True),
    sa.Column('date_obtenu_fourniture', sa.Date(), nullable=True),
    sa.Column('date_livraison', sa.Date(), nullable=False),
    sa.Column('nom_ou_restaurant', sa.String(length=250), nullable=False),
    sa.Column('kilo', sa.Float(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('lieu', sa.String(length=250), nullable=True),
    sa.Column('numero_telephone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fourniture_id'], ['fournitures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventes_date_livraison'), 'ventes', ['date_livraison'], unique=False)
    op.create_index(op.f('ix_ventes_date_obtenu_fourniture'), 'ventes', ['date_obtenu_fourniture'], unique=False)
    op.create_index(op.f('ix_ventes_fourniture_id'), 'ventes', ['fourniture_id'], unique=False)
    op.create_index(op.f('ix_ventes_id'), 'ventes', ['id'], unique=False)
    op.create_index(op.f('ix_ventes_nom_ou_restaurant'), 'ventes', ['nom_ou_restaurant'], unique=False)
    op.create_index(op.f('ix_ventes_product_id'), 'ventes', ['product_id'], unique=False)

    op.create_table('commandes_retour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('nom_produit_texte', sa.String(length=150), nullable=False),
    sa.Column('fourniture_id', sa.Integer(), nullable=True),
    sa.Column('origine', sa.String(length=200), nullable=False),
    sa.Column('kilo', sa.Float(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fourniture_id'], ['fournitures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commandes_retour_id'), 'commandes_retour', ['id'], unique=False)
    op.create_index(op.f('ix_commandes_retour_origine'), 'commandes_retour', ['origine'], unique=False)
    op.create_index(op.f('ix_commandes_retour_product_id'), 'commandes_retour', ['product_id'], unique=False)
    op.create_index(op.f('ix_commandes_retour_fourniture_id'), 'commandes_retour', ['fourniture_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commandes_retour_fourniture_id'), table_name='commandes_retour')
    op.drop_index(op.f('ix_commandes_retour_product_id'), table_name='commandes_retour')
    op.drop_index(op.f('ix_commandes_retour_origine'), table_name='commandes_retour')
    op.drop_index(op.f('ix_commandes_retour_id'), table_name='commandes_retour')
    op.drop_table('commandes_retour')

    op.drop_index(op.f('ix_ventes_product_id'), table_name='ventes')
    op.drop_index(op.f('ix_ventes_nom_ou_restaurant'), table_name='ventes')
    op.drop_index(op.f('ix_ventes_id'), table_name='ventes')
    op.drop_index(op.f('ix_ventes_fourniture_id'), table_name='ventes')
    op.drop_index(op.f('ix_ventes_date_obtenu_fourniture'), table_name='ventes')
    op.drop_index(op.f('ix_ventes_date_livraison'), table_name='ventes')
    op.drop_table('ventes')

    op.drop_index(op.f('ix_fournitures_product_id'), table_name='fournitures')
    op.drop_index(op.f('ix_fournitures_nom_fournisseur'), table_name='fournitures')
    op.drop_index(op.f('ix_fournitures_id'), table_name='fournitures')
    op.drop_index(op.f('ix_fournitures_date_obtenu'), table_name='fournitures')
    op.drop_table('fournitures')
    # ### end Alembic commands ###
